apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-data
  labels:
    storage-type: nfs
    storage-source: metrics-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volumes/metrics
    server: dns.futuregen.cloud
  persistentVolumeReclaimPolicy: Retain
