apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-metrics-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      storage-type: nfs
      storage-source: metrics
  volumeName: metrics-data
