apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-main-db-alertmanager-main-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: alertmanager-main-db-alertmanager-main-2
    namespace: openshift-monitoring
  nfs:
    path: /volumes/pvs/alertmanager-main-db-alertmanager-main-2
    server: fulab1-02-nfs1.fulab1.futuregen.lab
  persistentVolumeReclaimPolicy: Retain
