version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: /volumes
http:
  addr: registry.test.cloud:5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /volumes/cert/registry.test.cloud.crt
    key: /volumes/cert/registry.test.cloud.key

health:
  storagedriver:
    enabled: true
    interval: 60s
    threshold: 3
