apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins
    namespace: jenkins
  nfs:
    path: /nfs1/jenkins
    server: l2-11-nfs1.lab2.dslee.lab
  persistentVolumeReclaimPolicy: Retain
