apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-registry
    namespace: default
  nfs:
    path: /volumes/pvs/registry
    server: fulab1-02-nfs1.fulab1.futuregen.lab
  persistentVolumeReclaimPolicy: Retain
