apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-es-ops-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: logging-es-ops-0
    namespace: openshift-logging
  nfs:
    path: /volumes/pvs/logging-es-ops-0
    server: fulab1-02-nfs1.fulab1.futuregen.lab
  persistentVolumeReclaimPolicy: Retain
