apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-cassandra-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      storage-type: nfs
      storage-source: cassandra-data
  volumeName: cassandra-data
