apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage
  labels:
    storage-type: nfs
    storage-source: registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volumes/registry
    server: dns.futuregen.cloud
  persistentVolumeReclaimPolicy: Retain
