apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      storage-type: nfs
      storage-source: registry
  volumeName: registry-storage
