apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv-1
  labels:
    storage-type: nfs
    storage-source: es-pv-1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volumes/logging-es-1
    server: dns.futuregen.cloud
  persistentVolumeReclaimPolicy: Retain
