apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-es-1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      storage-type: nfs
      storage-source: es-pv-1
  volumeName: es-pv-1
