apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      storage-type: nfs
      storage-source: logging-volume
  volumeName: logging-volume
