apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-cassandra-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: metrics-cassandra-1
    namespace: openshift-infra
  nfs:
    path: /volumes/pvs/metrics-cassandra-1
    server: fulab1-02-nfs1.fulab1.futuregen.lab
  persistentVolumeReclaimPolicy: Retain
